version: "3.8"
services:
  db:
    build: ./db
    image: horionyoda/mysql-teste:01
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
    volumes:
      - ./data:/var/lib/mysql
  web:
    build: ./web
    image: horionyoda/node-teste:01
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080